### ISSUE TITLE
What is h_img and e_img

### ISSUE THREAD

**Issue by sharkdeng** [schaugf/HEnorm_python#3]
Thank you for this concise code. The final output is 3 imgs, normalized img, h_img, and e_img. What are hematoxylin image and eosin image? And what the usage of them since eosin image is kind of blur. Thank you for clarification.

**Comment by schaugf** [comment]
Hi Shark,
The eosin and hematoxylin images are the result of synthetic stain
unmixing. They can be used for a few different things, but the normalized
H&E is probably more useful. For example, some IHC work is relying just on
hematoxylin without eosin, so unmixing the two generates a more relevant
dataset in that setting.
Thanks for your interest,
Geoff

**Comment by sharkdeng** [comment]
Thank you for the detailed explanation.
